openapi: 3.0.0
info:
  title: TMS Cascade Protection API
  description: |
    API endpoints for cascade protection and safe deletion in the Teacher Management System.
    
    These endpoints provide information about cascading relationships and allow safe deletion
    with warnings when related records will be affected.
  version: 1.0.0

paths:
  /api/cascade/school/{schoolId}:
    get:
      tags:
        - Cascade Protection
      summary: Get school cascade information
      description: |
        Retrieves information about what records will be affected if a school is deleted.
        This includes teachers, medical records, attachments, deputations, and posting histories.
      parameters:
        - name: schoolId
          in: path
          required: true
          description: School ID to check cascade information for
          schema:
            type: string
            example: "SCH001"
      responses:
        '200':
          description: Cascade information retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Cascade information retrieved successfully"
                  data:
                    type: object
                    properties:
                      schoolId:
                        type: string
                        example: "SCH001"
                      cascadeInfo:
                        type: object
                        properties:
                          teachers:
                            type: integer
                            description: Number of teachers in this school
                            example: 15
                          medicalRecords:
                            type: integer
                            description: Number of medical records for teachers in this school
                            example: 45
                          attachments:
                            type: integer
                            description: Number of attachments for teachers in this school
                            example: 8
                          deputations:
                            type: integer
                            description: Number of deputations for teachers in this school
                            example: 2
                          postingHistories:
                            type: integer
                            description: Number of posting histories for teachers in this school
                            example: 15
                      totalAffected:
                        type: integer
                        description: Total number of records that will be affected
                        example: 85
                      warning:
                        type: string
                        description: Warning message about the deletion impact
                        example: "Deleting this school will affect 85 related records"
        '404':
          description: School not found
        '403':
          description: Insufficient permissions
        '500':
          description: Internal server error

    delete:
      tags:
        - Cascade Protection
      summary: Safe delete school with cascade protection
      description: |
        Deletes a school with cascade protection. If related records exist, the deletion
        will be blocked unless the force parameter is set to true.
      parameters:
        - name: schoolId
          in: path
          required: true
          description: School ID to delete
          schema:
            type: string
            example: "SCH001"
        - name: force
          in: query
          required: false
          description: Force deletion even if cascade records exist
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: School deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "School deleted successfully"
                  data:
                    type: object
                    description: Deleted school information
        '400':
          description: Deletion blocked due to cascade relationships
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "School deletion will affect related records"
                  data:
                    type: object
                    properties:
                      teachers:
                        type: integer
                        example: 15
                      medicalRecords:
                        type: integer
                        example: 45
                      attachments:
                        type: integer
                        example: 8
                      deputations:
                        type: integer
                        example: 2
                      postingHistories:
                        type: integer
                        example: 15
                  error:
                    type: string
                    example: "This will delete 15 teachers, 45 medical records, 8 attachments, 2 deputations, and 15 posting histories. Use force=true to proceed."
        '404':
          description: School not found
        '403':
          description: Insufficient permissions
        '500':
          description: Internal server error

  /api/cascade/teacher/{teacherId}:
    get:
      tags:
        - Cascade Protection
      summary: Get teacher cascade information
      description: |
        Retrieves information about what records will be affected if a teacher is deleted.
        This includes medical records, attachments, deputations, and posting histories.
      parameters:
        - name: teacherId
          in: path
          required: true
          description: Teacher ID to check cascade information for
          schema:
            type: integer
            example: 123
      responses:
        '200':
          description: Cascade information retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Cascade information retrieved successfully"
                  data:
                    type: object
                    properties:
                      teacherId:
                        type: integer
                        example: 123
                      cascadeInfo:
                        type: object
                        properties:
                          medicalRecords:
                            type: integer
                            description: Number of medical records for this teacher
                            example: 3
                          attachments:
                            type: integer
                            description: Number of attachments for this teacher
                            example: 2
                          deputations:
                            type: integer
                            description: Number of deputations for this teacher
                            example: 1
                          postingHistories:
                            type: integer
                            description: Number of posting histories for this teacher
                            example: 4
                      totalAffected:
                        type: integer
                        description: Total number of records that will be affected
                        example: 10
                      warning:
                        type: string
                        description: Warning message about the deletion impact
                        example: "Deleting this teacher will affect 10 related records"
        '404':
          description: Teacher not found
        '403':
          description: Insufficient permissions
        '500':
          description: Internal server error

    delete:
      tags:
        - Cascade Protection
      summary: Safe delete teacher with cascade protection
      description: |
        Deletes a teacher with cascade protection. If related records exist, the deletion
        will be blocked unless the force parameter is set to true.
      parameters:
        - name: teacherId
          in: path
          required: true
          description: Teacher ID to delete
          schema:
            type: integer
            example: 123
        - name: force
          in: query
          required: false
          description: Force deletion even if cascade records exist
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Teacher deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Teacher deleted successfully"
                  data:
                    type: object
                    description: Deleted teacher information
        '400':
          description: Deletion blocked due to cascade relationships
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Teacher deletion will affect related records"
                  data:
                    type: object
                    properties:
                      medicalRecords:
                        type: integer
                        example: 3
                      attachments:
                        type: integer
                        example: 2
                      deputations:
                        type: integer
                        example: 1
                      postingHistories:
                        type: integer
                        example: 4
                  error:
                    type: string
                    example: "This will delete 3 medical records, 2 attachments, 1 deputation, and 4 posting histories. Use force=true to proceed."
        '404':
          description: Teacher not found
        '403':
          description: Insufficient permissions
        '500':
          description: Internal server error

  /api/cascade/user/{userId}:
    get:
      tags:
        - Cascade Protection
      summary: Get user cascade information
      description: |
        Retrieves information about what records will be affected if a user is deleted.
        This includes refresh tokens, audit logs, and medical records entered by the user.
      parameters:
        - name: userId
          in: path
          required: true
          description: User ID to check cascade information for
          schema:
            type: integer
            example: 456
      responses:
        '200':
          description: Cascade information retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Cascade information retrieved successfully"
                  data:
                    type: object
                    properties:
                      userId:
                        type: integer
                        example: 456
                      cascadeInfo:
                        type: object
                        properties:
                          refreshTokens:
                            type: integer
                            description: Number of active refresh tokens
                            example: 2
                          medicalRecordsEntered:
                            type: integer
                            description: Number of medical records entered by this user
                            example: 15
                          auditLogs:
                            type: integer
                            description: Number of audit log entries for this user
                            example: 45
                      totalAffected:
                        type: integer
                        description: Total number of records that will be affected
                        example: 62
                      canDelete:
                        type: boolean
                        description: Whether the user can be deleted (false if they have entered medical records)
                        example: true
                      warning:
                        type: string
                        description: Warning message about the deletion impact
                        example: "Deleting this user will affect 62 related records"
        '404':
          description: User not found
        '403':
          description: Insufficient permissions
        '500':
          description: Internal server error

    delete:
      tags:
        - Cascade Protection
      summary: Safe delete user with cascade protection
      description: |
        Deletes a user with cascade protection. If the user has entered medical records,
        the deletion will be blocked unless the force parameter is set to true.
      parameters:
        - name: userId
          in: path
          required: true
          description: User ID to delete
          schema:
            type: integer
            example: 456
        - name: force
          in: query
          required: false
          description: Force deletion even if cascade records exist
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: User deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "User deleted successfully"
                  data:
                    type: object
                    description: Deleted user information
        '400':
          description: Deletion blocked due to cascade relationships
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "User deletion will affect related records"
                  data:
                    type: object
                    properties:
                      refreshTokens:
                        type: integer
                        example: 2
                      medicalRecordsEntered:
                        type: integer
                        example: 15
                      auditLogs:
                        type: integer
                        example: 45
                  error:
                    type: string
                    example: "This will delete 2 refresh tokens, 15 medical records, and 45 audit logs. Use force=true to proceed."
        '404':
          description: User not found
        '403':
          description: Insufficient permissions
        '500':
          description: Internal server error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from login or OTP verification

security:
  - BearerAuth: []
