openapi: 3.0.0
info:
  title: Districts API
  version: 1.0.0
tags:
  - name: Districts
paths:
  /api/districts:
    get:
      tags: [Districts]
      summary: List districts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/DistrictsListResponse'
    post:
      tags: [Districts]
      summary: Create district
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: './components.yaml#/components/schemas/District' }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/DistrictResponse'
  /api/districts/{id}:
    get:
      tags: [Districts]
      summary: Get district by ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/DistrictResponse'
    put:
      tags: [Districts]
      summary: Update district by ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: './components.yaml#/components/schemas/District' }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/DistrictResponse'
    delete:
      tags: [Districts]
      summary: Delete district by ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200': { description: OK }


