openapi: 3.0.0
info:
  title: Locations API
  version: 1.0.0
tags:
  - name: Locations
paths:
  /api/locations/districts:
    get:
      tags: [Locations]
      summary: Get active districts (id, name)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/DistrictsListResponse'
  /api/locations/rd-blocks:
    get:
      tags: [Locations]
      summary: Get RD blocks (with district names)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/RdBlocksListResponse'
    post:
      tags: [Locations]
      summary: Create RD block
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                district_id: { type: integer }
              required: [name, district_id]
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/RdBlockResponse'
  /api/locations/rd-blocks/all:
    get:
      tags: [Locations]
      summary: Get all RD blocks (including inactive)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/RdBlocksListResponse'
  /api/locations/rd-blocks/active:
    get:
      tags: [Locations]
      summary: Get active RD blocks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/RdBlocksListResponse'
  /api/locations/villages:
    get:
      tags: [Locations]
      summary: Get villages (with rd_block and district names)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/VillagesListResponse'
  /api/locations/villages/all:
    get:
      tags: [Locations]
      summary: Get all villages (including inactive)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/VillagesListResponse'
  /api/locations/villages/active:
    get:
      tags: [Locations]
      summary: Get active villages
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/VillagesListResponse'
  /api/locations/rd-blocks/{districtId}:
    get:
      tags: [Locations]
      summary: Get RD blocks by district ID
      parameters:
        - in: path
          name: districtId
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/RdBlocksListResponse'
  /api/locations/villages/{rdBlockId}:
    get:
      tags: [Locations]
      summary: Get villages by RD block ID
      parameters:
        - in: path
          name: rdBlockId
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/VillagesListResponse'
  
  /api/locations/rd-blocks/{id}:
    put:
      tags: [Locations]
      summary: Update RD block
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                district_id: { type: integer }
                is_active: { type: boolean }
              required: [name, district_id]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/RdBlockResponse'
    delete:
      tags: [Locations]
      summary: Soft delete RD block
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/ApiSuccess'
  /api/locations/rd-blocks/{id}/permanent:
    delete:
      tags: [Locations]
      summary: Hard delete RD block
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/ApiSuccess'
  /api/locations/habitations:
    post:
      tags: [Locations]
      summary: Create habitation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                rd_block_id: { type: integer }
              required: [name, rd_block_id]
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/VillageResponse'
  /api/locations/habitations/{id}:
    put:
      tags: [Locations]
      summary: Update habitation
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                rd_block_id: { type: integer }
                is_active: { type: boolean }
              required: [name, rd_block_id]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/VillageResponse'
    delete:
      tags: [Locations]
      summary: Soft delete habitation
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/ApiSuccess'
  /api/locations/habitations/{id}/permanent:
    delete:
      tags: [Locations]
      summary: Hard delete habitation
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/ApiSuccess'
