openapi: 3.0.0
info:
  title: OTP Authentication API
  description: API endpoints for OTP-based authentication system
  version: 1.0.0
  contact:
    name: TMS API Support
    email: support@tms.gov.in

tags:
  - name: OTP Authentication
    description: OTP-based login system for teachers

paths:
  /api/otp-auth/send-otp:
    post:
      tags:
        - OTP Authentication
      summary: Send OTP to phone number
      description: Sends a 6-digit OTP to the provided phone number for teacher authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phone
              properties:
                phone:
                  type: string
                  description: Phone number to send OTP to
                  example: "6909701606"
                  pattern: "^[0-9]{10}$"
      responses:
        '200':
          description: OTP sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "OTP sent successfully"
        '400':
          description: Bad request - Invalid phone number or user not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Invalid phone number format"
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "User not found with this phone number"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Failed to send OTP"

  /api/otp-auth/verify-otp:
    post:
      tags:
        - OTP Authentication
      summary: Verify OTP and login
      description: Verifies the provided OTP and logs in the teacher user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phone
                - otp
              properties:
                phone:
                  type: string
                  description: Phone number used for OTP
                  example: "6909701606"
                otp:
                  type: string
                  description: 6-digit OTP code
                  example: "123456"
                  pattern: "^[0-9]{6}$"
      responses:
        '200':
          description: OTP verified successfully and user logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Login successful"
                  token:
                    type: string
                    description: JWT authentication token
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          description: Bad request - Invalid OTP or expired OTP
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Invalid or expired OTP"
        '404':
          description: OTP not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "OTP not found or expired"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Failed to verify OTP"

  /api/otp-auth/resend-otp:
    post:
      tags:
        - OTP Authentication
      summary: Resend OTP
      description: Resends OTP to the same phone number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phone
              properties:
                phone:
                  type: string
                  description: Phone number to resend OTP to
                  example: "6909701606"
      responses:
        '200':
          description: OTP resent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "OTP resent successfully"
        '400':
          description: Bad request - Invalid phone number or no existing OTP
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "No existing OTP found for this phone number"
        '429':
          description: Too many requests - Rate limited
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Please wait before requesting another OTP"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Failed to resend OTP"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          description: Unique user identifier
          example: 1
        username:
          type: string
          description: Username
          example: "teacher"
        email:
          type: string
          description: Email address
          example: "teacher@tms.gov.in"
        phone:
          type: string
          description: Phone number
          example: "6909701606"
        role:
          type: string
          enum: [super_admin, admin, deo, sdeo, hoi, teacher]
          description: User role
          example: "teacher"
        is_active:
          type: boolean
          description: Whether user account is active
          example: true
        created_at:
          type: string
          format: date-time
          description: Account creation timestamp
          example: "2024-01-15T10:30:00Z"
      required:
        - id
        - username
        - email
        - role
        - is_active
        - created_at

    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          description: Error message
          example: "An error occurred"
        error:
          type: string
          description: Detailed error information (development only)
          example: "Database connection failed"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from OTP verification

security:
  - BearerAuth: []
