openapi: 3.0.0
info:
  title: Religions API
  version: 1.0.0
tags:
  - name: Religions
paths:
  /api/religions:
    get:
      tags: [Religions]
      summary: List religions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/ReligionsListResponse'
    post:
      tags: [Religions]
      summary: Create religion
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: './components.yaml#/components/schemas/Religion' }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/ReligionResponse'
  /api/religions/{id}:
    get:
      tags: [Religions]
      summary: Get religion by ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/ReligionResponse'
    put:
      tags: [Religions]
      summary: Update religion by ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: './components.yaml#/components/schemas/Religion' }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/ReligionResponse'
    delete:
      tags: [Religions]
      summary: Delete religion by ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200': { description: OK }


