openapi: 3.0.0
info:
  title: Role-Based Access Control (RBAC) System
  description: Documentation for the role-based access control system and permissions
  version: 1.0.0
  contact:
    name: TMS API Support
    email: support@tms.gov.in

tags:
  - name: Roles & Permissions
    description: Role hierarchy and permission system

paths:
  /api/roles:
    get:
      tags:
        - Roles & Permissions
      summary: Get all available roles
      description: Retrieves information about all available roles in the system
      responses:
        '200':
          description: Roles retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      roles:
                        type: array
                        items:
                          $ref: '#/components/schemas/Role'
                      hierarchy:
                        $ref: '#/components/schemas/RoleHierarchy'
                      permissions:
                        $ref: '#/components/schemas/Permissions'

  /api/roles/{role}/permissions:
    get:
      tags:
        - Roles & Permissions
      summary: Get permissions for a specific role
      description: Retrieves all permissions available to a specific role
      parameters:
        - name: role
          in: path
          required: true
          description: Role name
          schema:
            type: string
            enum: [super_admin, admin, deo, sdeo, hoi, teacher]
            example: "admin"
      responses:
        '200':
          description: Permissions retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      role:
                        type: string
                        example: "admin"
                      permissions:
                        type: array
                        items:
                          type: string
                        example: ["users.read", "users.create", "users.update", "schools.read"]
                      display_name:
                        type: string
                        example: "Administrator"
                      description:
                        type: string
                        example: "Administrative access to manage schools, teachers, and system data"
        '404':
          description: Role not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/roles/hierarchy:
    get:
      tags:
        - Roles & Permissions
      summary: Get role hierarchy
      description: Retrieves the role hierarchy with levels and descriptions
      responses:
        '200':
          description: Role hierarchy retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/RoleHierarchy'

  /api/roles/permissions/all:
    get:
      tags:
        - Roles & Permissions
      summary: Get all permissions
      description: Retrieves all available permissions grouped by category
      responses:
        '200':
          description: All permissions retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Permissions'

components:
  schemas:
    Role:
      type: object
      properties:
        name:
          type: string
          description: Role identifier
          example: "super_admin"
        display_name:
          type: string
          description: Human-readable role name
          example: "Super Administrator"
        description:
          type: string
          description: Role description
          example: "Full system access including user management and role assignment"
        level:
          type: integer
          description: Role hierarchy level (higher number = more privileges)
          example: 6
        permissions:
          type: array
          items:
            type: string
          description: List of permissions for this role
          example: ["users.read", "users.create", "users.update", "users.delete"]

    RoleHierarchy:
      type: object
      description: Role hierarchy levels (higher number = more privileges)
      properties:
        super_admin:
          type: integer
          description: Super Administrator level
          example: 6
        admin:
          type: integer
          description: Administrator level
          example: 5
        deo:
          type: integer
          description: District Education Officer level
          example: 4
        sdeo:
          type: integer
          description: Sub-Division Education Officer level
          example: 3
        hoi:
          type: integer
          description: Head of Institution level
          example: 2
        teacher:
          type: integer
          description: Teacher level
          example: 1

    Permissions:
      type: object
      description: All available permissions grouped by category
      properties:
        users:
          type: object
          properties:
            read:
              type: string
              description: Read user information
              example: "users.read"
            create:
              type: string
              description: Create new users
              example: "users.create"
            update:
              type: string
              description: Update user information
              example: "users.update"
            delete:
              type: string
              description: Delete users
              example: "users.delete"
            manage_roles:
              type: string
              description: Assign and modify user roles
              example: "users.manage_roles"
        schools:
          type: object
          properties:
            read:
              type: string
              description: Read school information
              example: "schools.read"
            create:
              type: string
              description: Create new schools
              example: "schools.create"
            update:
              type: string
              description: Update school information
              example: "schools.update"
            delete:
              type: string
              description: Delete schools
              example: "schools.delete"
            export:
              type: string
              description: Export school data
              example: "schools.export"
        teachers:
          type: object
          properties:
            read:
              type: string
              description: Read teacher information
              example: "teachers.read"
            read_own:
              type: string
              description: Read own teacher information
              example: "teachers.read_own"
            create:
              type: string
              description: Create new teachers
              example: "teachers.create"
            update:
              type: string
              description: Update teacher information
              example: "teachers.update"
            delete:
              type: string
              description: Delete teachers
              example: "teachers.delete"
            export:
              type: string
              description: Export teacher data
              example: "teachers.export"
        medical_records:
          type: object
          properties:
            read:
              type: string
              description: Read medical records
              example: "medical_records.read"
            read_own:
              type: string
              description: Read own medical records
              example: "medical_records.read_own"
            create:
              type: string
              description: Create medical records
              example: "medical_records.create"
            update:
              type: string
              description: Update medical records
              example: "medical_records.update"
            delete:
              type: string
              description: Delete medical records
              example: "medical_records.delete"
        master_data:
          type: object
          properties:
            read:
              type: string
              description: Read master data
              example: "master_data.read"
            create:
              type: string
              description: Create master data
              example: "master_data.create"
            update:
              type: string
              description: Update master data
              example: "master_data.update"
            delete:
              type: string
              description: Delete master data
              example: "master_data.delete"
        reports:
          type: object
          properties:
            read:
              type: string
              description: Read reports
              example: "reports.read"
            read_own:
              type: string
              description: Read own reports
              example: "reports.read_own"
            create:
              type: string
              description: Create reports
              example: "reports.create"
            export:
              type: string
              description: Export reports
              example: "reports.export"
        analytics:
          type: object
          properties:
            read:
              type: string
              description: Read analytics data
              example: "analytics.read"
            read_own:
              type: string
              description: Read own analytics data
              example: "analytics.read_own"

    RolePermissions:
      type: object
      description: Permissions for each role
      properties:
        super_admin:
          type: array
          items:
            type: string
          description: Super Administrator permissions
          example: ["users.read", "users.create", "users.update", "users.delete", "users.manage_roles", "schools.read", "schools.create", "schools.update", "schools.delete", "schools.export", "teachers.read", "teachers.create", "teachers.update", "teachers.delete", "teachers.export", "medical_records.read", "medical_records.create", "medical_records.update", "medical_records.delete", "master_data.read", "master_data.create", "master_data.update", "master_data.delete", "reports.read", "reports.create", "reports.export", "analytics.read"]
        admin:
          type: array
          items:
            type: string
          description: Administrator permissions
          example: ["schools.read", "schools.create", "schools.update", "schools.delete", "schools.export", "teachers.read", "teachers.create", "teachers.update", "teachers.delete", "teachers.export", "medical_records.read", "medical_records.create", "medical_records.update", "medical_records.delete", "master_data.read", "master_data.create", "master_data.update", "master_data.delete", "reports.read", "reports.create", "reports.export", "analytics.read"]
        deo:
          type: array
          items:
            type: string
          description: District Education Officer permissions
          example: ["schools.read", "schools.update", "schools.export", "teachers.read", "teachers.update", "teachers.export", "medical_records.read", "master_data.read", "reports.read", "reports.export", "analytics.read"]
        sdeo:
          type: array
          items:
            type: string
          description: Sub-Division Education Officer permissions
          example: ["schools.read", "schools.update", "schools.export", "teachers.read", "teachers.update", "teachers.export", "medical_records.read", "master_data.read", "reports.read", "reports.export", "analytics.read"]
        hoi:
          type: array
          items:
            type: string
          description: Head of Institution permissions
          example: ["schools.read", "schools.update", "schools.export", "teachers.read", "teachers.update", "teachers.export", "medical_records.read", "master_data.read", "reports.read", "reports.export", "analytics.read"]
        teacher:
          type: array
          items:
            type: string
          description: Teacher permissions
          example: ["teachers.read_own", "medical_records.read_own", "reports.read_own", "analytics.read_own"]

    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          description: Error message
          example: "Role not found"
        error:
          type: string
          description: Detailed error information (development only)
          example: "Invalid role identifier"

  examples:
    RoleHierarchyExample:
      summary: Role Hierarchy Example
      description: Example showing the role hierarchy levels
      value:
        super_admin: 6
        admin: 5
        deo: 4
        sdeo: 3
        hoi: 2
        teacher: 1

    SuperAdminPermissionsExample:
      summary: Super Admin Permissions
      description: Example of Super Administrator permissions
      value:
        - "users.read"
        - "users.create"
        - "users.update"
        - "users.delete"
        - "users.manage_roles"
        - "schools.read"
        - "schools.create"
        - "schools.update"
        - "schools.delete"
        - "schools.export"
        - "teachers.read"
        - "teachers.create"
        - "teachers.update"
        - "teachers.delete"
        - "teachers.export"
        - "medical_records.read"
        - "medical_records.create"
        - "medical_records.update"
        - "medical_records.delete"
        - "master_data.read"
        - "master_data.create"
        - "master_data.update"
        - "master_data.delete"
        - "reports.read"
        - "reports.create"
        - "reports.export"
        - "analytics.read"

    TeacherPermissionsExample:
      summary: Teacher Permissions
      description: Example of Teacher permissions
      value:
        - "teachers.read_own"
        - "medical_records.read_own"
        - "reports.read_own"
        - "analytics.read_own"
