openapi: 3.0.0
info:
  title: School Types API
  version: 1.0.0
tags:
  - name: School Types
paths:
  /api/school-types:
    get:
      tags: [School Types]
      summary: List school types
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/SchoolTypesListResponse'
    post:
      tags: [School Types]
      summary: Create school type
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: './components.yaml#/components/schemas/SchoolType' }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/SchoolTypeResponse'
  /api/school-types/{id}:
    get:
      tags: [School Types]
      summary: Get school type by ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/SchoolTypeResponse'
    put:
      tags: [School Types]
      summary: Update school type by ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: './components.yaml#/components/schemas/SchoolType' }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/SchoolTypeResponse'
    delete:
      tags: [School Types]
      summary: Delete school type by ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200': { description: OK }


