openapi: 3.0.0
info:
  title: Users API
  version: 1.0.0
tags:
  - name: Users
components:
  schemas:
    $ref: './components.yaml#/components/schemas'
paths:
  /api/users/login:
    post:
      tags: [Users]
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Unauthorized

  /api/users/refresh:
    post:
      tags: [Users]
      summary: Refresh access token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshResponse'

  /api/users/logout:
    post:
      tags: [Users]
      summary: Logout and revoke current refresh token
      responses:
        '200': { description: OK }

  /api/users/password/reset-request:
    post:
      tags: [Users]
      summary: Request password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetRequest'
      responses:
        '200': { description: OK }

  /api/users/password/reset:
    post:
      tags: [Users]
      summary: Reset password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordReset'
      responses:
        '200': { description: OK }


